# Generated by Django 5.2.2 on 2025-06-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='أعمالي', max_length=200)),
                ('description', models.TextField(default='بعض من المشاريع التي عملت عليها')),
            ],
        ),
    ]
