# Generated by Django 5.2.2 on 2025-06-06 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_workssection'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='works_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='main.workssection'),
        ),
    ]
